tester: Use prefix for rtems_tools by default
Commit 72c684eff2cd932b4948e21902680a93473340c3 removed the default
value of rtems_tools.  If the --rtems--tools option was omitted the
rtems-test command printed lots of

	error: run.cfg:61: macro '%{rtems_tools}' not found

error messages.