rtemstoolkit/libiberty: Add missing file
This fixes the following build error for --host=x86_64-w64-mingw32:

rtemstoolkit/libiberty.a(pex-win32.c.18.o): in function `win32_spawn':
rtemstoolkit/libiberty/pex-win32.c:643: undefined reference to `writeargv'

Update #4969.